# -*- coding: utf-8 -*-
"""Inclusivity_Score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe4FysgrYR5077XH_-zpqTseepT0WQnR
"""

import pandas as pd
import numpy as np

!pip install textblob

from textblob import TextBlob

user_input = input("Please enter your text so we can provide a feedback on its Inclusivity")

blob = TextBlob(user_input)
sentiment = blob.sentiment

Sentiment_Analysis_Placeholder = "Thats ok"

suggestions_dictionary = {
    "nigger": "fine gentleman of african descent",
    "Gypsy": "Romani",
    "faggot": "member of LGBTQ+",
    "go fuck yourself": "i dont like your attitude"
}




if sentiment.polarity > 0.75:
  Sentiment_Analysis_Placeholder = "Thats really good!"

elif sentiment.polarity > 0.5:
  Sentiment_Analysis_Placeholder = "Thats good"

elif sentiment.polarity < 0:
  Sentiment_Analysis_Placeholder = "Thats bad"

  print ("Heres how to improve it:")


  updated_input = user_input
  for key, value in suggestions_dictionary.items():
      updated_input = updated_input.replace(key, value)

  print (updated_input)



elif sentiment.polarity < -0.5:
  Sentiment_Analysis_Placeholder = "Thats really bad"

  print ("Heres how to improve it:")


  updated_input = user_input
  for key, value in suggestions_dictionary.items():
      updated_input = updated_input.replace(key, value)

  print (updated_input)

print (f" Your text score is {(sentiment.polarity *5) + 5 }.  {Sentiment_Analysis_Placeholder}")

sentiment

